#!/usr/bin/env python3
"""Batch generate .splattie files from portrait images using LAM CLI on GPU.

Calls LAM's inference runner for each image (handles FLAME tracking + 3DGS
reconstruction), then bundles the output PLY with shared FLAME skeleton
assets into a .splattie ZIP with a manifest.json that locks the format
version to the widget package.json version.

Usage (run from backend/vendor/LAM/):
    python ../../scripts/generate_splattie_batch.py \
        --images-dir /tmp/pexels \
        --output-dir /tmp/splattie_out
"""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path

from splattie.methods.bundle_common import (
    DEFAULT_STATES_HEAD,
    build_manifest,
    bundle_splattie,
    count_ply_vertices,
    read_widget_version,
)


def run_lam_inference(image_path: Path, name: str) -> Path:
    """Run LAM inference via CLI. Returns path to the generated offset PLY."""
    os.makedirs("tracking_output/preprocess", exist_ok=True)
    os.makedirs(f"tracking_output/export/{name}", exist_ok=True)

    import sys

    cmd = [
        sys.executable,
        "-m",
        "lam.launch",
        "infer.lam",
        "--config",
        "configs/inference/lam-20k-8gpu.yaml",
        "model_name=model_zoo/lam_models/releases/lam/lam-20k/step_045500/",
        f"image_input={image_path}",
        "save_ply=true",
        "save_img=true",
        "export_video=true",
        "export_mesh=false",
        "vis_motion=false",
        "render_fps=30",
        f"motion_seqs_dir=tracking_output/export/{name}/",
        "motion_img_dir=null",
        "rank=0",
        "nodes=0",
    ]
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = env.get("CUDA_VISIBLE_DEVICES", "0")
    env["PYTHONPATH"] = "." + (":" + env["PYTHONPATH"] if "PYTHONPATH" in env else "")

    result = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        print(f"  STDERR: {result.stderr[-500:]}")
        raise RuntimeError(f"LAM inference failed for {name}")

    return Path(f"exps/cano_gs/{name}_gs_offset.ply")


def find_absolute_ply(name: str) -> Path:
    """Find the absolute-position PLY generated by LAM (offset2xyz=False, rgb2sh=True)."""
    ply_path = Path(f"exps/cano_gs/{name}.ply")
    if not ply_path.exists():
        raise FileNotFoundError(f"Absolute PLY not found: {ply_path}")
    print(f"  Absolute PLY: {ply_path} ({ply_path.stat().st_size // 1024} KB)")
    return ply_path


def bundle_head_splattie(
    name: str,
    ply_path: Path,
    output_dir: Path,
    source_image_path: Path,
    widget_version: str,
) -> Path:
    """Bundle a LAM head PLY + shared FLAME rig + manifest into a `.splattie` ZIP."""
    splattie_path = output_dir / f"{name}.splattie"
    manifest = build_manifest(
        splat_filename=f"{name}.ply",
        num_gaussians=count_ply_vertices(ply_path),
        widget_version=widget_version,
        asset_type=AssetType.HEAD,
        rig=HEAD_RIG,
        source_image_path=source_image_path,
    )
    bundle_splattie(
        output_path=splattie_path,
        splat_path=ply_path,
        manifest=manifest,
        states=DEFAULT_STATES_HEAD,
    )
    size_kb = splattie_path.stat().st_size // 1024
    print(f"  Bundle: {splattie_path} ({size_kb} KB)")
    return splattie_path


def main():
    parser = argparse.ArgumentParser(description="Batch generate .splattie files")
    parser.add_argument("--images-dir", type=str, required=True)
    parser.add_argument("--output-dir", type=str, required=True)
    args = parser.parse_args()

    images_dir = Path(args.images_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    widget_version = read_widget_version()
    print(f"Widget version: {widget_version}\n")

    image_files = sorted(f for f in images_dir.iterdir() if f.suffix.lower() in (".jpg", ".jpeg", ".png"))

    if not image_files:
        print(f"No images found in {images_dir}")
        return

    print(f"Found {len(image_files)} images\n")

    for i, img_path in enumerate(image_files, 1):
        name = img_path.stem
        print(f"[{i}/{len(image_files)}] {img_path.name}")

        try:
            run_lam_inference(img_path, name)
            abs_ply = find_absolute_ply(name)
            bundle_head_splattie(name, abs_ply, output_dir, img_path, widget_version)
            print("  OK\n")
        except Exception as e:
            print(f"  FAILED: {e}\n")
            continue

    splattie_files = list(output_dir.glob("*.splattie"))
    print(f"Done! {len(splattie_files)} .splattie files in {output_dir}")


if __name__ == "__main__":
    main()
